config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'gruss' => 'pages#card', as: 'card'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def card
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Grusskarte</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<link href='https://fonts.googleapis.com/css?family=Amatic+SC|Satisfy|Sacramento|Petit+Formal+Script' rel='stylesheet' type='text/css'>  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/card.html.erb
<h2>Digital Interaktiv Fantastisches</h2>
<h1>
  <%= image_tag "ribbon.png", class: "ribbon" %>
  Geburtstags-Quiz für Claudia
  <%= image_tag "ribbon.png", class: "ribbon" %>
</h1>


<section class="container">
  <div class="postcard">
    <figure class="front">
      <div class="photo">
        <%= image_tag "tobi.jpg", class: "image_kids", title: "Bild von Tobias" %>
      </div>

      <form id="form_tobi">
        <p class="query">Was war Kleintobis Leibgericht?</p>
        <fieldset>
          <div>
            <input type="radio" id="answer1" name="frage_tobi" value="wrong"><label for="answer1">☐ Ente à l'orange</label>
          </div>
          <div>
            <input type="radio" id="answer2" name="frage_tobi" value="wrong"><label for="answer2">☐ Kutteln</label>
          </div>
          <div>
            <input type="radio" id="answer3" name="frage_tobi" value="right"><label for="answer3">☐ Rotkraut, Kartoffelbrei & Würstchen</label>
          </div>
        </fieldset>
      </form>
    </figure>

    <figure class="back">
      <p>Liebe Mama,</p>
      <p>alles Gute zum 50. Geburtstag!</P>
      <p>Wow schon ganz schön alt könnte man meinen... Ich finde das merkt man dir aber überhaupt nicht an „wink“-Emoticon Und deshalb wünsche ich dir zu deinem Geburtstag genauso viel Kraft, Muße, Kreativität, Liebenswürdigkeit, Überzeugung, Begeisterung, Einfühlsamkeit, Tierliebe, Engagement, Witz, Güte, Optimismus, Geduld, Energie und all deine anderen positiven Eigenschaften, wie du sie bisher immer hattest. Bleib einfach so, wie du bist!</p>
      <p>Ich hab dich lieb,<br>
      Tobi</p>
    </figure>
  </div>
</section>


<section class="container">
  <div class="postcard">
    <figure class="front">
      <div class="photo">
        <%= image_tag "Kidsbild1.JPG", class: "image_kids", title: "Bild von Jo" %>
      </div>

      <form>
        <p class="query">Welches ist das umstrittendste Spiel in der Familie?</p>
        <fieldset>
          <div>
            <input type="radio" id="jo_answer1" name="frage_jo" value="wrong"><label for="jo_answer1">☐ Malefitz</label><br>
          </div>
          <div>
            <input type="radio" id="jo_answer2" name="frage_jo" value="right"><label for="jo_answer2">☐ Monopoly</label><br>
          </div>
          <div>
            <input type="radio" id="jo_answer3" name="frage_jo" value="wrong"><label for="jo_answer3">☐ Kuhhandel</label><br>
          </div>
        </fieldset>
      </form>
    </figure>

    <figure class="back">
      <p>Liebe Claudia,</p>

<p>
Heute kann es regnen,<br>
stürmen oder schneien,<br>
denn du strahlst ja selber<br>
wie der Sonnenschein.<br>
Heut ist dein Geburtstag,<br>
darum feiern wir,<br>
alle deine Freunde<br>
freuen sich mit dir<br>
</p>

<p>Zu deinem Ehrentag wünsche Ich Dir Gelassenheit und die Weisheit, dass man für Kinderlieder nie zu alt wird. Auf weitere glückliche, kindliche und weise 50 Jahre.<br>
</p><p>
Deine Jo</p>


    </figure>
  </div>
</section>


<section class="container">
  <div class="postcard">
    <figure class="front">
      <div class="photo">
        <%= image_tag "Tobi2.JPG", class: "image_kids", title: "Bild von Tobias" %>
      </div>
      <form id="form_tobi">
        <p class="query">Wo waren wir im Urlaub, als Tim gerade geboren wurde?</p>
        <fieldset>
          <div>
            <input type="radio" id="answer51" name="frage_tobi" value="wrong"><label for="answer51">☐ Miami</label>
          </div>
          <div>
            <input type="radio" id="answer52" name="frage_tobi" value="wrong"><label for="answer52">☐ Afrika</label>
          </div>
          <div>
            <input type="radio" id="answer53" name="frage_tobi" value="right"><label for="answer53">☐ Föhr</label>
          </div>
        </fieldset>
      </form>
    </figure>

    <figure class="back">
      <p>Kinder, die noch zu Hause wohnen, überbringen ihre Glückwünsche persönlich :).</p>
    </figure>
  </div>
</section>

<section class="container">
  <div class="postcard">
    <figure class="front">
      <div class="photo">
        <%= image_tag "Familienbild1.JPG", class: "image_kids", title: "Bild von Tobias" %>
      </div>
      <form id="">
        <p class="query">Was verlernt man nie?</p>
        <fieldset>
          <div>
            <input type="radio" id="answer100" name="frage_tobi" value="wrong"><label for="answer100">☐ Sprachen</label>
          </div>
          <div>
            <input type="radio" id="answer101" name="frage_tobi" value="right"><label for="answer101">☐ Reiten</label>
          </div>
          <div>
            <input type="radio" id="answer102" name="frage_tobi" value="right"><label for="answer102">☐ Ski-Fahren</label>
          </div>
        </fieldset>
      </form>
    </figure>

    <figure class="back">
      <div class="photo">
        <%= image_tag "Kinder1.JPG", class: "image_kids", title: "Bild von Tobias" %>
      </div>
      <div class="photo">
        <%= image_tag "Kinder2.JPG", class: "image_kids", title: "Bild von Tobias" %>
      </div>
    </figure>
  </div>

</section>

app/views/pages/home.html.erb
<h1 style="margin-top: 30px">
  Alles Gute zum Geburtstag
</h1>

<%= link_to image_tag("present.png"), card_url, class: "present" %>


<h2 style="">
  <%= link_to "Zu den Geschenken", card_url %>
</h1>